siristechnology/nepaltoday-api

- package.json
- src/database/typeDefs.graphql
- yarn.lock
- adding category feild for gql endpoint
> Modify db schema

- package.json
- src/database/__tests__/resolvers.storeFcm.test.js
- src/database/resolvers.js
- src/database/typeDefs.graphql
- src/utils/arryUtil.test.js
- yarn.lock
- db with user-schema tag is used
- mutation for creating user with fcbtoken and countrycode is made
> Nep 129 create mutation api

- src/database/resolvers.js
- src/helper/articleHelper.js
- src/helper/articleHelper.test.js
- src/utils/arrayUtil.js
- sorting algorithm is modified and timestamp is added on payload
> modify-sorting-algo: 

- .vscode/settings.json
- src/db-service/index.js
- src/db-service/newsDbService.integration.js
- src/jobs/NotificationTrigger/__tests__/notificationTime.test.js
- src/jobs/NotificationTrigger/config.js
- src/jobs/NotificationTrigger/index.js
- src/jobs/NotificationTrigger/notificationTime.js
@syuraj sir minor changes xa... related to notificationTime helper
> W5-added tests for notificationTime helper

- src/jobs/NotificationTrigger/http.js
- src/jobs/NotificationTrigger/index.js
> w5-notification issues related changes

- .github/workflows/nodejs.yml
- .gitignore
- jest.config.js
> Upload test coverage to codecov

- src/constants/portal.js
- src/db-service/scripts/source-data.js
- src/jobs/NewsCrawlerTrigger/__tests__/manual-scrapper.test.js
- src/jobs/NewsCrawlerTrigger/config/selector.js
- src/jobs/NewsCrawlerTrigger/config/url.js
- src/jobs/NewsCrawlerTrigger/content-crawler.js
- src/jobs/NewsCrawlerTrigger/linkCrawler.js
@syuraj @shrestha2lt8  sir i have added news source bbc nepali please review
> NEP-154 add news source bbc nepali

- src/db-service/scripts/source-data.js
@syuraj @shrestha2lt8  sir please review garidinu hola
> feature update source-data file

- package.json
- src/db-service/scripts/source-data-caller.js
- src/db-service/scripts/source-data.js
@syuraj @shrestha2lt8  sir please review garidinu hola.. yo feature.. malai better hola jasto lagyo 👍
> Feature source insert through command

- src/jobs/NotificationTrigger/__tests__/NotificationTrigger.integration.js
- src/jobs/NotificationTrigger/index.js
- src/jobs/NotificationTrigger/notificationHelper.js
- src/jobs/NotificationTrigger/notificationTime.js
- src/jobs/NotificationTrigger/pushNotificationSender.js
- src/jobs/NotificationTrigger/usersWithCurrentTime.js
@syuraj  sir yo commit review gardinu
> NEP-152 notification issues

- index.js
- package.json
- yarn.lock
@syuraj sir updated express and used express.json() instead of bodyParser package
> added newer version of express

- src/db-service/NotificationDbService.js
- src/db-service/notificationDbService.integration.js
@syuraj  sir i will merge it later approve garidinu hola
> added tests and fixed issue while saving notification

- src/jobs/NewsCrawlerTrigger/index.js
- src/utils/arrayUtil.js
- src/utils/arryUtil.test.js
@syuraj  sir remove slash and remaining white spaces while saving topic
> added remove slash helper

- src/db-service/newsDbService.js
- yarn.lock
@syuraj  sir populated source for latest news to be used while opening notification
> populate source for latest news

- src/database/resolvers.js
- src/database/typeDefs.graphql
- src/jobs/NotificationTrigger/__tests__/pushNotificationSender.integration.js
- src/jobs/NotificationTrigger/pushNotificationSender.js
@syuraj  sir added graphql query for single article to be fetched from article id
> NEP-159 added graphql query for single article

- src/jobs/NotificationTrigger/__tests__/pushNotificationSender.integration.js
- src/jobs/NotificationTrigger/notificationHelper.js
@syuraj  sir only included article id in notification data
> NEP-159 included only article id in notification data

- docs/pull_request_template.md
- package.json
- src/jobs/NewsCrawlerTrigger/__tests__/runner.test.js
- src/jobs/NewsCrawlerTrigger/config/news-source-config.json
- src/jobs/NewsCrawlerTrigger/runner.js
- yarn.lock
-   [ ] Include Jira Stroy No. in Title
-   [x] Write Unit Tests
> wip: using news-crawler to scrape news using chromium browser

- src/jobs/NewsCrawlerTrigger/config/url.js
> Nep-183 : News from all sources

- src/db-service/database/mongooseSchema.js
> NEP-11 :  Deleted old articles and tweets older than 7 days

- src/db-service/database/mongooseSchema.js
> NEP-11 : Delete old article branch

- src/database/resolvers.js
- src/database/typeDefs.graphql
- src/db-service/database/mongooseSchema.js
- src/db-service/districtCoronaDbService.js
- src/db-service/index.js
- src/jobs/districtCorona/index.js
- src/jobs/job-runner/start-jobs.js
> NEP-204 : Added districts corona info

- package.json
- src/jobs/NewsCrawlerTrigger/index.js
- src/jobs/NewsCrawlerTrigger/runner.js
- src/server.js
- yarn.lock
> NEP-208 : Error report

- src/database/typeDefs.graphql
- src/db-service/database/mongooseSchema.js
- src/db-service/scripts/trending-handles.js
- src/db-service/scripts/update-db.js
- src/db-service/trendingDbService.js
- src/jobs/trending/index.js
> NEP-216 : all trendings added

- package.json
- src/db-service/database/mongooseSchema.js
- src/db-service/scripts/update-db.js
- src/jobs/facebookPost/index.js
> NEP-219 : Facebook poster

- src/jobs/NotificationTrigger/notificationTime.js
- src/jobs/NotificationTrigger/pushNotificationSender.js
- src/jobs/facebookPost/index.js
> remove notif unused log

- package.json
- src/jobs/facebookPost/index.js
> fb puppeter library from news crawler library

- src/config/twitter-handles.js
- src/db-service/database/mongooseSchema.js
> twiter handle added

- src/jobs/facebookPost/index.js
> NEP-228 : facebook link added

- src/jobs/facebookPost/index.js
> fb time increased

- package.json
- src/jobs/NewsCrawlerTrigger/helper.js
- src/jobs/NewsCrawlerTrigger/index.js
- src/jobs/facebookPost/index.js
- src/server.js
- yarn.lock
> NEP-227 : article title repitition added

- src/config/category.js
- src/config/twitter-handles.js
- src/db-service/trendingDbService.js
- src/jobs/trending/index.js
> trending handles correcetd

- src/jobs/facebookPost/index.js
> fb time decreased test

- src/jobs/facebookPost/index.js
> NEP-234 : FacebookPostWorking

- src/config/category.js
- src/config/news-source-config.json
- src/jobs/NewsCrawlerTrigger/index.js
- src/jobs/trendingTopics/index.js
> NEP-247 : Headline home

- src/config/category.js
- src/config/news-source-config.json
> NEP-258 : Merge समाज and बिचार category into single category समाज

- src/database/typeDefs.graphql
- src/db-service/database/mongooseSchema.js
- src/jobs/districtCorona/__tests__/districtCorona.test.js
- src/jobs/districtCorona/index.js
- src/jobs/job-runner/start-jobs.js
> NEP-259 : Corona stats corrected and source added

- src/jobs/job-runner/start-jobs.js
> corona job time changed to 1 hour

- src/database/typeDefs.graphql
- src/db-service/database/mongooseSchema.js
- src/jobs/corona/index.js
- src/jobs/facebookPost/index.js
- src/jobs/trendingTopics/index.js
> Nep260 source corona

- src/database/typeDefs.graphql
- src/db-service/database/mongooseSchema.js
- src/db-service/trendingDbService.js
- src/jobs/job-runner/start-jobs.js
- src/jobs/trending/index.js
> NEP-262 : trending issue solved

- src/database/typeDefs.graphql
- src/db-service/database/mongooseSchema.js
> created data graphql schema

- src/jobs/trending/index.js
> NEP-271 : trending images size increased

- src/jobs/NewsCrawlerTrigger/index.js
> minor console erorr corrected

- src/config/fm.js
- src/database/resolvers.js
- src/database/typeDefs.graphql
> NEP-269 : Play fm radio station on background

- package.json
> package name slightly changed

- src/config/fm.js
- src/database/typeDefs.graphql
> adding province name to fm list

- src/config/fm.js
- src/database/resolvers.js
- src/database/typeDefs.graphql
- src/db-service/database/mongooseSchema.js
> NEP-273 : province add

- src/database/typeDefs.graphql
- src/jobs/districtCorona/metricsJob.js
- src/jobs/districtCorona/tests/districtCorona.test.js
> NEP-278 :  New cases added to graphql schema

- src/jobs/districtCorona/tests/districtCorona.test.js
> new cases adding

- src/database/resolvers.js
- src/database/typeDefs.graphql
> NEP-273 : Removing fav radio added

- src/database/resolvers.js
> NEP-273 : Fix duplicate fav issue

- src/database/resolvers.js
- src/database/typeDefs.graphql
- src/db-service/database/mongooseSchema.js
> Nep 4 read article track

- src/jobs/NotificationTrigger/notificationTime.js
> corona notification time fixed

- src/jobs/NotificationTrigger/notificationTime.js
> NEP-282 : Duplicate notification error fixed

- src/db-service/UserDbService.js
- src/db-service/database/mongooseSchema.js
- src/jobs/NotificationTrigger/index.js
- src/jobs/NotificationTrigger/pushNotificationSender.js
> NEP-257 : Not sending notif to inactive users

- src/config/fm.js
> NEP-294 : Added fm stations

- src/config/fm.js
> FM list sorted

- src/config/fm.js
> Fm list sorting

- src/config/fm.js
- src/database/__tests__/calculateTotalWeights.test.js
- src/database/calculateTotalWeights.js
- src/database/resolvers.js
- src/database/typeDefs.graphql
- src/db-service/UserDbService.js
- src/db-service/database/mongooseSchema.js
> NEP-292 : article category weight added on the basis of read articles

- src/config/fm.js
> not working fm list removed

- package.json
- src/config/news-source-config.json
- src/jobs/job-runner/start-jobs.js
- src/jobs/newsChecker/index.js
- yarn.lock
> NEP-191 : send mail when any news source is not working

- src/database/typeDefs.graphql
> article total weight changed to float

- src/database/__tests__/resolvers.getArticles.integration.js
- src/database/__tests__/resolvers.getArticles.test.js
- src/jobs/job-runner/start-jobs.js
> NEP-292 : sort articles as per user preference test added

- src/database/resolvers.js
- src/database/typeDefs.graphql
- src/db-service/database/mongooseSchema.js
> Nep 225 news like

- src/jobs/newsChecker/index.js
> NEP-191 : Mail sending test

- src/jobs/job-runner/start-jobs.js
- src/jobs/newsChecker/index.js
> Email send

- src/jobs/newsChecker/index.js
> NEP-191 : Email sending through nodemailer try

- src/jobs/job-runner/start-jobs.js
> NEP-191 : setting check news source and send mail time to 24 hours

- src/config/news-source-config.json
- src/database/resolvers.js
- src/database/typeDefs.graphql
> Two fm api integrated into one, halokhabar content issue

- src/config/twitter-handles.js
- src/jobs/TwitterTrigger/index.js
> NEP-306 : Twitter errortojson error solved

- package.json
- src/config/news-source-config.json
- src/jobs/NewsCrawlerTrigger/dateConverter.js
- src/jobs/NewsCrawlerTrigger/index.js
- yarn.lock
> Nep 317 : fetch published date from cartoon articles

- package.json
- yarn.lock
> updating news crawler library

- src/config/twitter-handles.js
- src/database/resolvers.js
> NEP-313-Unrelated news issue

- src/config/news-source-config.json
- src/db-service/database/mongooseSchema.js
> Cartoon double issue

- package.json
- src/jobs/NewsCrawlerTrigger/index.js
> Cartoon title made unique

- src/config/news-source-config.json
- src/jobs/NewsCrawlerTrigger/dateConverter.js
> NEP-337 : correcting news source

- src/database/resolvers.js
- src/database/typeDefs.graphql
- src/db-service/database/mongooseSchema.js
- src/db-service/trendingTagDbService.js
- src/jobs/job-runner/start-jobs.js
- src/jobs/trendingTags/index.js
> NEP-305 : trending tag added

- src/database/resolvers.js
- src/database/typeDefs.graphql
- src/db-service/database/mongooseSchema.js
> NEP-350 : Api for admin panel category wise read articles stat made
